In [1]:
import pandas as pd

In [14]:
clinical_data = pd.read_csv("./../data/ADNI_clinical_characteristics.csv")

clinical_data.head()

,subject_id,visit,research_group,MH4CARD,VSWEIGHT,VSWTUNIT,VSHEIGHT,VSHTUNIT,VSBPSYS,VSBPDIA,PTGENDER,PTDOBYY,subject_date,IHSYMPTOM,IHPRESENT,IHSEVER,IHNUM,TYPE
0,002_S_0295,sc,CN,0.0,74.5,2.0,176.9,2.0,130.0,67.0,1.0,1921.0,2006-04-04,NaN,NaN,NaN,NaN,NaN
1,002_S_0413,sc,CN,1.0,61.4,2.0,169.2,2.0,116.0,56.0,2.0,1929.0,2006-04-06,NaN,NaN,NaN,NaN,NaN
2,002_S_0529,f,AD,1.0,70.9,2.0,175.3,2.0,129.0,64.0,1.0,1916.0,2006-05-04,NaN,NaN,NaN,NaN,NaN
3,002_S_0559,sc,CN,0.0,93.1,2.0,184.6,2.0,127.0,53.0,1.0,1927.0,2006-05-11,NaN,NaN,NaN,NaN,NaN
4,002_S_0619,sc,AD,0.0,82.2,2.0,181.2,2.0,132.0,67.0,1.0,1928.0,2006-05-18,NaN,NaN,NaN,NaN,NaN

In [ ]:
clinical_data["BMI"] = clinical_data.VSWEIGHT / (clinical_data.VSHEIGHT ** 2)

# height units 1 for in 2 for cm
# weight units 1 for lb, 2 for kg
lbs = clinical_data.VSWEIGHT
lbs[clinical_data.VSWTUNIT == 2] = clinical_data.VSWEIGHT[clinical_data.VSWTUNIT == 2] * 2.20462

ins = clinical_data.VSHEIGHT
ins[clinical_data.VSHTUNIT == 2] = clinical_data.VSHEIGHT[clinical_data.VSHTUNIT == 2] * 0.393701

clinical_data["BMI"] = 703 * lbs / (ins ** 2)
clinical_data.head()
print(clinical_data["BMI"].isna().sum())

4423

/var/folders/4j/0g3dxy6901134lp72sg7z5sm0000gp/T/ipykernel_70869/3188784217.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lbs[clinical_data.VSWTUNIT == 2] = clinical_data.VSWEIGHT[clinical_data.VSWTUNIT == 2] * 2.20462
/var/folders/4j/0g3dxy6901134lp72sg7z5sm0000gp/T/ipykernel_70869/3188784217.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ins[clinical_data.VSHTUNIT == 2] = clinical_data.VSHEIGHT[clinical_data.VSHTUNIT == 2] * 0.393701